// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesInfoService.DataAccess.Models
{
    public partial class Sale
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public int ManagerId { get; set; }
        public int ProductId { get; set; }
        public int ClientId { get; set; }
        public DateTime Date { get; set; }
        public decimal Cost { get; set; }

        [ForeignKey("ClientId")]
        public virtual Client Client { get; set; }
        
        [ForeignKey("ManagerId")]
        public virtual Manager Manager { get; set; }
        
        [ForeignKey("ProductId")]
        public virtual Product Product { get; set; }
    }
}