// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SalesInfoService.DataAccess.Models
{
    public partial class Sale
    {
        public int Id { get; set; }
        public int ManagerId { get; set; }
        public int ProductId { get; set; }
        public int ClientId { get; set; }
        public DateTime Date { get; set; }
        public decimal Cost { get; set; }

        public virtual Client Client { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Product Product { get; set; }
    }
}